from aiogram.dispatcher.filters.state import StatesGroup, State
class Cases(StatesGroup):
	C1 = State()
	H1 = State()
	M1 = State()
	C2 = State()
	H2 = State()
	M2 = State()
	C3 = State()
	H3 = State()
	M3 = State()
	C4 = State()
	H4 = State()
	M4 = State()
	C5 = State()
	H5 = State()
	M5 = State()
	AFTER_ALL = State()
	NOT_ALL = State()
	AFTER_NOT_ALL = State()
	NEW1 = State()
	NEW2 = State()